version: '3.7' 

# Define services for Docker containers
services:

  # MariaDB service
  mariadb:
    container_name: mymariadb # Container name for MariaDB service
    build:
      context: requirements/mariadb  # Build context for MariaDB service
      dockerfile: Dockerfile # Dockerfile for MariaDB service
    image: mymariadb # Image name for MariaDB service
    env_file: .env # Load environment variables from .env file
    networks:
      - inception # Connect the MariaDB service to the inception network
    volumes:
      - mariadb:/var/lib/mysql # Mount MariaDB data
    restart: on-failure # Restart the container on failure
    init: true  # Initialize the container
    expose:
      - "3306"  # Expose port 3306 for MySQL

  # WordPress service
  wordpress:
    container_name: mywordpress
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: mywordpress
    env_file: .env
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress # Mount WordPress files
    restart: on-failure
    init: true
    ports:
      - "9000"  # Expose port 9000 for PHP-FPM

  # Nginx service
  nginx:
    container_name: mynginx
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    image: mynginx
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress  # Mount WordPress files
    depends_on:
      - wordpress
    init: true
    restart: on-failure
    ports:
      - "443:443"  # Expose port 443 for HTTPS

# Define custom networks for Docker containers
networks:
  inception:
    name: inception

# Define volumes for persistent data storage
volumes:
  mariadb: # Volume for MariaDB data
    name: mariadb-vlm # Volume name for MariaDB data
    driver: local # Use the local driver
    driver_opts: # Set driver options
      type: 'none' # Set the mount type to none
      o: 'bind' # Bind the volume for sync between host and container
      device: '/home/ababdelo/data/mariadb'  # Path to MariaDB data directory
      
  wordpress:
    name: wordpress-vlm
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ababdelo/data/wordpress'